SET APPVEYOR_REPO_BRANCH=%BRANCHNAME%
SET APPVEYOR_REPO_TAG=%TAG%
SET APPVEYOR_BUILD_NUMBER=%BUILDNUMBER%
SET APPVEYOR_BUILD_VERSION=%VERSION%
SET UMBRACO_PACKAGE_PRERELEASE_SUFFIX=%SUFFIX%

ECHO APPVEYOR_REPO_BRANCH : %APPVEYOR_REPO_BRANCH%
ECHO APPVEYOR_REPO_TAG : %APPVEYOR_REPO_TAG%
ECHO APPVEYOR_BUILD_NUMBER : %APPVEYOR_BUILD_NUMBER%
ECHO APPVEYOR_BUILD_VERSION : %APPVEYOR_BUILD_VERSION%

CALL build\tools\NuGet\NuGet.exe restore src\Our.Umbraco.InnerContent.sln
CALL "%programfiles(x86)%\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\MsBuild.exe" build\package.proj